# Generated by Django 5.1.4 on 2024-12-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='administratifstaff',
            name='role',
            field=models.CharField(default='administratifStaff', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='doctor', max_length=50),
        ),
        migrations.AddField(
            model_name='labtechnician',
            name='role',
            field=models.CharField(default='LabTechnician', max_length=50),
        ),
        migrations.AddField(
            model_name='nurse',
            name='role',
            field=models.CharField(default='Nurse', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=50),
        ),
        migrations.AddField(
            model_name='radiologist',
            name='role',
            field=models.CharField(default='Radiologist', max_length=50),
        ),
    ]
