# Generated by Django 5.1.4 on 2024-12-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_administratifstaff_role_doctor_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='NSS',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
