# Generated by Django 5.1.4 on 2024-12-27 22:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administratifStaff',
            fields=[
                ('idAdministratifStaff', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=70)),
                ('passwrord', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='approvedMedications',
            fields=[
                ('idApprovedMedications', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('idDiagnostic', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('idHospital', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('idlabTechnician', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medecine',
            fields=[
                ('idMedecine', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('idObservation', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('idRadiologist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('idConsultation', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('chiefComplaint', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('diagnostic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='api.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='EHR',
            fields=[
                ('idEHR', models.AutoField(primary_key=True, serialize=False)),
                ('administratifStaff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ehr_staff', to='api.administratifstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('idDoctor', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=200)),
                ('ehr', models.ManyToManyField(blank=True, related_name='doctors', to='api.ehr')),
            ],
        ),
        migrations.CreateModel(
            name='BiologyReport',
            fields=[
                ('idBiologyReport', models.AutoField(primary_key=True, serialize=False)),
                ('bloodSugarLevel', models.FloatField()),
                ('bloodPressure', models.FloatField()),
                ('chelesterolLevel', models.FloatField()),
                ('completeBloodCount', models.FloatField()),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='biology_reports', to='api.doctor')),
                ('lab_technician', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='biology_reports', to='api.labtechnician')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('idMedicalCertificate', models.AutoField(primary_key=True, serialize=False)),
                ('requesed', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='api.doctor')),
                ('ehr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='api.ehr')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('idNurse', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=200)),
                ('ehr', models.ManyToManyField(blank=True, related_name='nurses', to='api.ehr')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idPatient', models.AutoField(primary_key=True, serialize=False)),
                ('NSS', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('dateOfBirth', models.DateField()),
                ('address', models.CharField(max_length=70)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('mutual', models.CharField(max_length=45)),
                ('contactPerson', models.CharField(max_length=45)),
                ('bloodType', models.CharField(choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-')], default='O_POSITIVE', max_length=11)),
                ('gender', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('ehr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='api.ehr')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('idPrescription', models.AutoField(primary_key=True, serialize=False)),
                ('isValid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='api.doctor')),
                ('ehr', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='api.ehr')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Duration', models.IntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_treatments', to='api.medecine')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_treatments', to='api.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='prescription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='api.prescription'),
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('idRadiologyReport', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=45)),
                ('imageData', models.BinaryField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to='api.doctor')),
                ('radiologist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to='api.radiologist')),
            ],
        ),
    ]
