# Generated by Django 5.1.4 on 2024-12-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administratifstaff',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='administratifstaff',
            old_name='passwrord',
            new_name='password',
        ),
    ]
