# Generated by Django 5.1.4 on 2024-12-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_email_administratifstaff_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administratifstaff',
            old_name='idAdministratifStaff',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='approvedmedications',
            old_name='idApprovedMedications',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='biologyreport',
            old_name='idBiologyReport',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='idConsultation',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='diagnostic',
            old_name='idDiagnostic',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='idDoctor',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='ehr',
            old_name='idEHR',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='idHospital',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='labtechnician',
            old_name='idlabTechnician',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='medecine',
            old_name='idMedecine',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='medicalcertificate',
            old_name='idMedicalCertificate',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='idNurse',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='idObservation',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='idPatient',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='idPrescription',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='radiologist',
            old_name='idRadiologist',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='radiologyreport',
            old_name='idRadiologyReport',
            new_name='id',
        ),
    ]
