# Generated by Django 5.1.4 on 2025-01-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patient_address_alter_patient_contactperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
