# Generated by Django 5.1.4 on 2024-12-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patient_nss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ehr',
            name='administratifStaff',
        ),
        migrations.AddField(
            model_name='ehr',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ehrs', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='ehr',
            name='creator_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ehrs', to='api.administratifstaff'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='NSS',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
