# Generated by Django 5.1.4 on 2024-12-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_patient_nss'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareProvided',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('care_actions', models.TextField()),
                ('ehr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_provided', to='api.ehr')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_provided', to='api.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdministered',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('care_provided', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_administered', to='api.careprovided')),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.medecine')),
            ],
        ),
        migrations.DeleteModel(
            name='approvedMedications',
        ),
        migrations.RenameField(
            model_name='biologyreport',
            old_name='chelesterolLevel',
            new_name='cholesterolLevel',
        ),
        migrations.AddField(
            model_name='biologyreport',
            name='ehr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biology_reports', to='api.ehr'),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='ehr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to='api.ehr'),
        ),
        migrations.AlterField(
            model_name='biologyreport',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biology_reports', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='biologyreport',
            name='lab_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biology_reports', to='api.labtechnician'),
        ),
        migrations.AddField(
            model_name='observation',
            name='care_provided',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='api.careprovided'),
        ),
    ]
