# Generated by Django 5.1.4 on 2025-01-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_careprovided_medicationadministered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiologicalAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('patient_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('tests_to_conduct', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biological_assessments', to='api.doctor')),
                ('ehr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biological_assessments', to='api.ehr')),
            ],
        ),
    ]
