# Generated by Django 5.1.4 on 2025-01-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_biologicalassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalassessment',
            name='doctor',
        ),
    ]
