# Generated by Django 5.1.4 on 2025-01-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_radiologyassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalassessment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biological_assessments', to='api.doctor'),
        ),
    ]
