# Generated by Django 5.1.4 on 2025-01-01 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_biologicalassessment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyassessment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_assessments', to='api.doctor'),
        ),
    ]
