# Generated by Django 5.1.4 on 2025-01-02 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_radiologyassessment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltreatment',
            name='medicine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.medecine'),
        ),
    ]
