# Generated by Django 5.1.4 on 2025-01-02 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_medicaltreatment_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologyreport',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biologyreport',
            name='lab_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biology_reports', to='api.labtechnician'),
        ),
    ]
