# Generated by Django 5.1.4 on 2025-01-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_biologyreport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalassessment',
            name='biology_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='api.biologyreport'),
        ),
        migrations.AddField(
            model_name='radiologyassessment',
            name='radiology_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='api.radiologyreport'),
        ),
    ]
