# Generated by Django 5.1.4 on 2025-01-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_biologicalassessment_biology_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyreport',
            name='radiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to='api.radiologist'),
        ),
    ]
