# Generated by Django 5.1.4 on 2025-01-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_sgph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgph',
            name='email',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sgph',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
