# Generated by Django 5.1.4 on 2025-01-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_radiologyreport_radiologist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyreport',
            name='imageData',
            field=models.ImageField(blank=True, null=True, upload_to='radiology_reports/'),
        ),
    ]
