# Generated by Django 5.1.4 on 2025-01-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_sgph_email_alter_sgph_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sgph',
            options={},
        ),
        migrations.AlterModelManagers(
            name='sgph',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='sgph',
            name='username',
        ),
    ]
